# This workflow download the backup and save it as a repo artifact

name: download backup

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get the zip...
      run: |
        wget -O backup.tar.gz http://dromotherm.ddns.net/backup/download?apikey=${{ secrets.RWKEY }}
        ls -al
    - name: Upload the zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dromotherm_backup
        path: backup.tar.gz
